### ISSUE TITLE
Update kubernetes repository

### ISSUE THREAD

**Issue by git-ogawa** [git-ogawa/setup_docker#12]
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

> Note: The legacy package repositories (apt.kubernetes.io and yum.kubernetes.io) have been [deprecated and frozen starting from September 13, 2023](https://kubernetes.io/blog/2023/08/31/legacy-package-repository-deprecation/). Using the [new package repositories hosted at pkgs.k8s.io](https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/) is strongly recommended and required in order to install Kubernetes versions released after September 13, 2023. The deprecated legacy repositories, and their contents, might be removed at any time in the future and without a further notice period. The new package repositories provide downloads for Kubernetes versions starting with v1.24.0.

so need to update the repository to `pkgs.k8s.io`.

https://github.com/git-ogawa/setup_kube_cluster/blob/main/roles/kubernetes/tasks/install.yml#L21-L30
```yml
    - name: Download the Google Cloud public signing key
      ansible.builtin.get_url:
        url: https://dl.k8s.io/apt/doc/apt-key.gpg
        dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg
        mode: "0644"
      become: true


    - name: Add kubernetes repository
      ansible.builtin.apt_repository:
        repo: >
          deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg]
          https://apt.kubernetes.io/ kubernetes-xenial main
```
